### ISSUE TITLE
test

### ISSUE THREAD

**Issue by arkbg1** [BitVote/bitvote.github.io#12]
ping

**Comment by byebyeblueberry** [comment]
Hey guys,

Do you want me to do transcribe the 21/12 Tech Talk vid?

Happy Neeeeew Year! 2015, it's the year for execution!!

xx

Sarah Claire


C: +27 (0) 71 244 0406

http://sarahclairep.tumblr.com/ <http://sarahclairepicton.blogspot.com>

**Comment by arkbg1** [comment]
https://docs.google.com/document/d/1r5xnYxoMjsvrHFBVUQDZDqb9rDrrLl0ezWn_T6SlVYc/edit?usp=drive_web

**Comment by byebyeblueberry** [comment]
Right!

Thanks! :/

Sarah Claire


C: +27 (0) 71 244 0406

http://sarahclairep.tumblr.com/ <http://sarahclairepicton.blogspot.com>
