### ISSUE TITLE
Dont show button if user already registered

### ISSUE THREAD

**Issue by o-jasper** [BitVote/bitvote.github.io#9]
Looking  at it, not sure how to do it yet, might take people with ~seconds of registered time as not having registered?

**Comment by o-jasper** [comment]
:url

**Comment by byebyeblueberry** [comment]
Guys. Girls. (alwaysshould be someone you really loveeee)

So forth.

Give me something to transcribe/do. Please! The city is burning. Anything
to transcribe/check for facts/names/grammar etc?

Also, social media-wise ---> any help needed with this? Can have a great
product, but if it isn't marketed... Combining street with online - not
losing the integrity of 'street' (tangible, print, something that is not
recycled in an hour)... Creating a global database too.

Anyway, been a long day so please excuse whatever errors you might pick up!

So it goes.

#11:11

Sarah Claire


C: +27 (0) 71 244 0406

http://sarahclairep.tumblr.com/ <http://sarahclairepicton.blogspot.com>
